import pandas as pd
import os
import datetime

from function import get_output_dirs, MODEL_FAMILY

# ============================================================
#  LOAD SUMMARY DATA (CSV with mean metrics and confidence intervals)
# ============================================================

def load_summary(summary_path):
    if not os.path.exists(summary_path):
        raise FileNotFoundError(f"File not found: {summary_path}")
    return pd.read_csv(summary_path)


def load_statistical_results(wilcoxon_path, ttest_path, delong_path):
    results = {}
    if os.path.exists(wilcoxon_path):
        results["wilcoxon"] = pd.read_csv(wilcoxon_path)
    else:
        results["wilcoxon"] = None

    if os.path.exists(ttest_path):
        results["ttest"] = pd.read_csv(ttest_path)
    else:
        results["ttest"] = None

    if os.path.exists(delong_path):
        results["delong"] = pd.read_csv(delong_path)
    else:
        results["delong"] = None

    return results


# ============================================================
#  BUILD MARKDOWN CONTENT
# ============================================================

def generate_markdown(summary, dirs):
    now = datetime.datetime.now().strftime("%Y-%m-%d %H:%M")

    md = []

    md.append(f"# 📊 Encoder Evaluation Report\n")
    md.append(f"**Generated:** {now}\n")
    md.append("---\n")

    md.append("## 🎯 Objective\n")
    md.append("Verify the robustness and reliability of the pipeline based on embeddings generated by modern models (E5-base, E5-large, GTE-large).\n")

    md.append("## 📘 Evaluated Models\n")
    for model in summary["model"]:
        md.append(f"- **{model}**")

    md.append("\n---\n")

    # ============================
    # METRICS WITH CI
    # ============================

    md.append("## 📈 Metric results with confidence intervals (Bootstrap 10,000)\n")

    md.append(summary.to_markdown(index=False))
    md.append("\n\n---\n")

    # ============================
    # CHARTS INCLUDED IN REPORT
    # ============================

    md.append("## 📉 ROC Curve Comparison\n")
    roc_path = os.path.join(dirs["graphics"], "ROC_comparison.png")
    real_roc_path = "../graphics/ROC_comparison.png"
    if os.path.exists(roc_path):
        md.append(f"![ROC Comparison]({real_roc_path})\n")

    md.append("\n---\n")

    md.append("## 🧩 Confusion Matrix\n")
    for model in summary["model"]:
        cm_path = os.path.join(dirs["graphics"], f"CM_{model}.png")
        real_cm_path = f"../graphics/CM_{model}.png"
        if os.path.exists(cm_path):
            md.append(f"### {model}\n")
            md.append(f"![CM {model}]({real_cm_path})\n")

    md.append("\n---\n")

    boxplot_path = os.path.join(dirs["results"], "BOXPLOT_metrics.png")
    real_boxplot_path = "../results/BOXPLOT_metrics.png"
    if os.path.exists(boxplot_path):
        md.append("## 📦 Bootstrapped Metric Boxplot\n")
        md.append(f"![Boxplot]({real_boxplot_path})\n")

    md.append("\n---\n")

    meanci_path = os.path.join(dirs["results"], "MeanCI_metrics.png")
    real_meanci_path = "../results/MeanCI_metrics.png"
    if os.path.exists(meanci_path):
        md.append("## 📐 Mean ± Confidence Interval\n")
        md.append("Mean metric per model with 95% bootstrap confidence interval (thin whisker) and ±1 standard deviation (thick whisker).\n")
        md.append(f"![Mean and Confidence Interval]({real_meanci_path})\n")

    md.append("\n---\n")

    family_path = os.path.join(dirs["results"], "FamilyComparison_metrics.png")
    real_family_path = "../results/FamilyComparison_metrics.png"
    if os.path.exists(family_path):
        md.append("## 🧬 Model Family Comparison\n")
        md.append("Bootstrap metric distributions pooled by model family: general-purpose vs. biomedical vs. biomedical sentence-transformers.\n")
        md.append(f"![Model Family Comparison]({real_family_path})\n")

    md.append("\n---\n")

    # ============================
    # ERROR ANALYSIS
    # ============================

    error_summary_path = os.path.join(dirs["results"], "error_summary.csv")
    if os.path.exists(error_summary_path):
        md.append("## 🩺 Error Analysis\n")
        md.append("Misclassified cases (false positives / false negatives) are traced back to the original clinical record for every model, using the fold validation indices saved during training.\n")

        df_error_summary = pd.read_csv(error_summary_path)
        md.append("### Error rates per model\n")
        md.append(df_error_summary.to_markdown(index=False))
        md.append("\n\n")

        error_rates_path = os.path.join(dirs["results"], "ErrorAnalysis_rates.png")
        real_error_rates_path = "../results/ErrorAnalysis_rates.png"
        if os.path.exists(error_rates_path):
            md.append(f"![Error Rates]({real_error_rates_path})\n")

        feature_dev_path = os.path.join(dirs["results"], "ErrorAnalysis_feature_deviation.png")
        real_feature_dev_path = "../results/ErrorAnalysis_feature_deviation.png"
        if os.path.exists(feature_dev_path):
            md.append("### Clinical feature deviation: misclassified vs. correctly classified\n")
            md.append("Standardized mean difference per clinical feature, pooled across all models (positive = higher in misclassified cases).\n")
            md.append(f"![Feature Deviation]({real_feature_dev_path})\n")

        hardest_cases_path = os.path.join(dirs["results"], "hardest_cases.csv")
        if os.path.exists(hardest_cases_path):
            df_hardest = pd.read_csv(hardest_cases_path)
            md.append("### Hardest cases (most frequently misclassified across models)\n")
            md.append(df_hardest.head(10).to_markdown(index=False))
            md.append("\n\n")

        md.append("---\n")

    # ============================
    # STATISTICAL TESTS
    # ============================

    stat_results = load_statistical_results(
        wilcoxon_path=os.path.join(dirs["results"], "wilcoxon_comparison.csv"),
        ttest_path=os.path.join(dirs["results"], "ttest_comparison.csv"),
        delong_path=os.path.join(dirs["results"], "delong_comparison.csv"),
    )
    if stat_results["wilcoxon"] is not None or stat_results["ttest"] is not None or stat_results["delong"] is not None:
        md.append("## 🧪 Statistical Tests\n")
        md.append("This section reports pairwise comparisons between model bootstrap metrics using Wilcoxon signed-rank tests, paired t-tests, and DeLong AUC comparisons.\n")

        if stat_results["wilcoxon"] is not None:
            md.append("### Wilcoxon Signed-Rank Test\n")
            md.append("The Wilcoxon test compares paired bootstrap distributions for each model pair.\n")
            md.append(stat_results["wilcoxon"].to_markdown(index=False))
            md.append("\n\n")

        if stat_results["ttest"] is not None:
            md.append("### Paired t-test\n")
            md.append("The paired t-test compares paired bootstrap means for each model pair.\n")
            md.append(stat_results["ttest"].to_markdown(index=False))
            md.append("\n\n")

        if stat_results["delong"] is not None:
            md.append("### DeLong AUC Comparison\n")
            md.append("The DeLong test compares AUC performance between model pairs on the same test labels.\n")
            md.append(stat_results["delong"].to_markdown(index=False))
            md.append("\n\n")

        md.append("---\n")
    else:
        md.append("## 🧪 Statistical Tests\n")
        md.append(f"No statistical test results were found. Ensure `{dirs['results']}/wilcoxon_comparison.csv`, `{dirs['results']}/ttest_comparison.csv`, and `{dirs['results']}/delong_comparison.csv` are generated before running report generation.\n")
        md.append("---\n")

    # ============================
    # HOLDOUT TEST SET EVALUATION
    # ============================

    holdout_path = os.path.join(dirs["results"], "holdout_evaluation.csv")
    if os.path.exists(holdout_path):
        md.append("## 🧾 Held-Out Test Set Evaluation\n")
        md.append(
            "Metrics on the 20% test split created in `preprocessing.py` and never used for "
            "training, threshold calibration, or the model comparisons above — the counterpart "
            "to the 5-fold cross-validation results, on data none of those steps ever saw.\n"
        )
        md.append(pd.read_csv(holdout_path).to_markdown(index=False))
        md.append("\n\n---\n")

    # ============================
    # DISCUSSION (computed from `summary`, not fixed text — see docs/CHANGES.md)
    # ============================

    md.append("## 🔍 Discussion and Observations\n")
    md.append(_build_discussion(summary))

    md.append("\n---\n")

    # ============================
    # CONCLUSIONS (computed from `summary` and `stat_results`, not fixed text)
    # ============================

    md.append("## 🏁 Conclusions\n")
    md.append(_build_conclusions(summary, stat_results))

    md.append("\n---\n")

    # ============================
    # IMPROVEMENTS
    # ============================

    md.append("## 🚀 Potential Improvements\n")
    md.append("""
- Test additional general-purpose or biomedical encoders beyond the ones already compared.
- Introduce a non-linear classifier (e.g. gradient boosting) as an additional comparison point.
- Apply probability calibration (e.g. Platt scaling) and report calibration curves, not only
  discrimination metrics (accuracy, F1, AUC).
- Run on the full Diabetes130 file instead of the 20,000-row stratified sample, to narrow the
  bootstrap confidence intervals further.
""")

    return "\n".join(md)


def _build_discussion(summary):
    """Observations computed from the actual `summary` DataFrame of this run, instead of a fixed
    block of text that could (and, in the version this replaced, did) describe a model that was
    not actually the best one for this specific dataset — see docs/CHANGES.md."""
    best_acc = summary.loc[summary["acc_mean"].idxmax()]
    best_f1 = summary.loc[summary["f1_mean"].idxmax()]
    best_auc = summary.loc[summary["auc_mean"].idxmax()]
    ci_width = summary["auc_ci_high"] - summary["auc_ci_low"]
    tightest = summary.loc[ci_width.idxmin()]

    lines = [
        f"- **{best_acc['model']}** has the highest mean accuracy in this run ({best_acc['acc_mean']:.4f}).",
        f"- **{best_f1['model']}** has the highest mean macro-F1 ({best_f1['f1_mean']:.4f}).",
        f"- **{best_auc['model']}** has the highest mean ROC-AUC ({best_auc['auc_mean']:.4f}), "
        f"95% bootstrap CI [{best_auc['auc_ci_low']:.4f}, {best_auc['auc_ci_high']:.4f}].",
        f"- **{tightest['model']}** has the narrowest AUC confidence interval "
        f"({ci_width.loc[tightest.name]:.4f} wide) — the most stable AUC estimate across the "
        "bootstrap resamples, independent of whether its mean AUC is also the highest.",
    ]
    family_auc = summary.assign(family=summary["model"].map(MODEL_FAMILY)).groupby("family")["auc_mean"].mean()
    if len(family_auc) > 1:
        best_family = family_auc.idxmax()
        lines.append(
            f"- Averaged by family, **{best_family}** has the highest mean AUC "
            f"({family_auc[best_family]:.4f}) among the families present in this run. This is "
            "a descriptive average, not a statistical test: see the DeLong comparison above "
            "for which specific pairwise differences are actually significant."
        )
    return "\n".join(lines)


def _build_conclusions(summary, stat_results):
    """Conclusions computed from `summary` and, where available, from the statistical test
    results already loaded for this report — not a fixed claim of general effectiveness that
    held regardless of what the data in a given run actually showed."""
    lines = [
        "- Every model in this run outperforms a trivial majority-class baseline on the "
        "SMOTE-balanced validation pool (50.0% accuracy, 0.333 macro-F1 by construction, since "
        "that pool is always exactly balanced) — see the accuracy/macro-F1 columns above.",
        "- Bootstrap resampling (10,000 iterations) gives every metric a reported confidence "
        "interval: treat a numerically higher mean as a meaningful difference only where the "
        "corresponding pairwise test below also reports significance, not from the ranking alone.",
    ]
    delong = stat_results.get("delong")
    if delong is not None and len(delong):
        sig = delong["significant"].astype(str).isin(["1", "1.0"])
        lines.append(
            f"- Of the {len(delong)} pairwise AUC comparisons (DeLong test), {int(sig.sum())} "
            f"are statistically significant at alpha=0.05 — see `delong_comparison.csv` for "
            "which specific pairs, rather than assuming every numeric difference is real."
        )
    return "\n".join(lines)


# ============================================================
#  MAIN
# ============================================================

def generate_report(dataset="heart_disease"):
    dirs = get_output_dirs(dataset)

    print("[INFO] Loading metric summary...")
    summary = load_summary(os.path.join(dirs["results"], "encoder_comparison_summary.csv"))

    print("[INFO] Generating markdown report...")
    md_content = generate_markdown(summary, dirs)

    md_path = os.path.join(dirs["reports"], "report.md")

    with open(md_path, "w") as f:
        f.write(md_content)

    print(f"[OK] Markdown report created: {md_path}")
    print("\n=== REPORT GENERATED SUCCESSFULLY ===")
