import pandas as pd
import os
import datetime

# ============================================================
#  LOAD SUMMARY DATA (CSV with mean metrics and confidence intervals)
# ============================================================

def load_summary(summary_path="datas/results/encoder_comparison_summary.csv"):
    if not os.path.exists(summary_path):
        raise FileNotFoundError(f"File not found: {summary_path}")
    return pd.read_csv(summary_path)


# ============================================================
#  BUILD MARKDOWN CONTENT
# ============================================================

def generate_markdown(summary):
    now = datetime.datetime.now().strftime("%Y-%m-%d %H:%M")

    md = []

    md.append(f"# 📊 Encoder Evaluation Report\n")
    md.append(f"**Generated:** {now}\n")
    md.append("---\n")

    md.append("## 🎯 Objective\n")
    md.append("Verify the robustness and reliability of the pipeline based on embeddings generated by modern models (E5-base, E5-large, GTE-large).\n")

    md.append("## 📘 Evaluated Models\n")
    for model in summary["model"]:
        md.append(f"- **{model}**")

    md.append("\n---\n")

    # ============================
    # METRICS WITH CI
    # ============================

    md.append("## 📈 Metric results with confidence intervals (Bootstrap 10,000)\n")

    md.append(summary.to_markdown(index=False))
    md.append("\n\n---\n")

    # ============================
    # CHARTS INCLUDED IN REPORT
    # ============================

    md.append("## 📉 ROC Curves\n")
    for model in summary["model"]:
        roc_path = f"datas/graphics/ROC_{model}.png"
        real_roc_path = f"../graphics/ROC_{model}.png"
        if os.path.exists(roc_path):
            md.append(f"### {model}\n")
            md.append(f"![ROC {model}]({real_roc_path})\n")

    md.append("\n---\n")

    md.append("## 🧩 Confusion Matrix\n")
    for model in summary["model"]:
        cm_path = f"datas/graphics/CM_{model}.png"
        real_cm_path = f"../graphics/CM_{model}.png"
        if os.path.exists(cm_path):
            md.append(f"### {model}\n")
            md.append(f"![CM {model}]({real_cm_path})\n")

    md.append("\n---\n")

    boxplot_path = "datas/results/BOXPLOT_metrics.png"
    real_boxplot_path = "../results/BOXPLOT_metrics.png"
    if os.path.exists(boxplot_path):
        md.append("## 📦 Bootstrapped Metric Boxplot\n")
        md.append(f"![Boxplot]({real_boxplot_path})\n")

    md.append("\n---\n")

    # ============================
    # DISCUSSION
    # ============================

    md.append("## 🔍 Discussion and Observations\n")
    md.append("""
- Larger embedding models (E5-large, GTE-large) generally show better performance.
- GTE-large tends to achieve higher ROC-AUC and tighter confidence intervals.
- Confusion matrices enable analysis of false positives and false negatives.
- Bootstrap is useful to verify metric stability and robustness.
""")

    md.append("\n---\n")

    # ============================
    # CONCLUSIONS
    # ============================

    md.append("## 🏁 Conclusions\n")
    md.append("""
- The embedding + linear classifier approach is effective.
- Modern encoders such as GTE-large demonstrate strong generalization.
- The pipeline is robust and stable, as confirmed by bootstrap 10,000.
""")

    md.append("\n---\n")

    # ============================
    # IMPROVEMENTS
    # ============================

    md.append("## 🚀 Potential Improvements\n")
    md.append("""
- Test additional encoders (bge-large, Jina-Embeddings, E5-mistral).
- Introduce a non-linear classifier (XGBoost, LightGBM).
- Apply advanced calibration techniques (Platt scaling).
- Add a larger clinical dataset to reduce variance error.
""")

    return "\n".join(md)


# ============================================================
#  MAIN
# ============================================================

def generate_report():

    print("[INFO] Loading metric summary...")
    summary = load_summary()

    print("[INFO] Generating markdown report...")
    md_content = generate_markdown(summary)

    md_path = "datas/reports/report.md"

    with open(md_path, "w") as f:
        f.write(md_content)

    print(f"[OK] Markdown report created: {md_path}")
    print("\n=== REPORT GENERATED SUCCESSFULLY ===")
